version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  app:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_URI: mongodb://root:password@mongodb:27017/
    volumes:
      - .:/app
    depends_on:
      - mongodb
    ports:
      - "3030:3000"

networks:
  testNetwork:

